blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('blog1.urls')),
    path('admin/', admin.site.urls),
]

blog1/urls.py
from django.urls import path
from blog1 import views
app_name = 'blog1'
urlpatterns = [
            # path('',views.landing,name= 'landing'),
            path('loggedin/',views.next1,name= 'after'),
            path('signup/',views.registration,name='signup'),
            path('congo/',views.congo,name='congo'),
            path('',views.userlogin,name='login'),
            path('blogs/',views.postmaker,name='blogs'),
            path('update/<str:pk>',views.update,name='update'),
            path('delete/<str:pk>',views.Delete,name='delete'),
            path('logout/',views.userlogout,name='logout'),
      


]

blog1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# class BlogContent(models.Model):
#         user = models.OneToOneField(User,on_delete=models.CASCADE)
#         Title = models.CharField(max_length = 20)
#         content = models.CharField(max_length=5000)
#         def __str__():
#             return self.user.username
#


class UserAddress(models.Model):
        user  = models.OneToOneField(User,related_name='stories',on_delete=models.CASCADE)
        address = models.CharField(max_length=5000,null=True)
        def __str__(self):
            return self.user.username

blog1/forms.py
from django import forms
from django.forms import ModelForm
from blog1.models import *
from django.contrib.auth.models import User

# class BlogForm(forms.ModelForm):
#     class Meta():
#         model = 'BlogContent'
#         fields = ('Title','content')


class authenticateform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields =('username','email')

# class BlogContent1Form(forms.ModelForm):
#     class Meta():
#         model = BlogContent11
#         fields = ('title','story')

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','email']

blog1/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from blog1.forms import *
from blog1.models import *
from django.contrib.auth.models import User
# Create your views here.

def userlogin(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('blog1:blogs'))
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('pass')
            user = authenticate(username= username,password=password)
            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('blog1:blogs'))
                else:
                    return HttpResponse("Account not active")
            else:
                print("someone tried to login and failed ")
                print(f"Username :{username} and password :{password}")
                return HttpResponse("Invalid login credentials")

        else:
            return render(request,'blog1/login.html',context={})

# @login_required
def next1(request):
    return render(request,'blog1/after.html',context={})

@login_required
def userlogout(request):
    logout(request)
    return render(request,'blog1/login.html')
#
def registration(request):
    registered = False
    if request.method == "POST":


        user_form = authenticateform(request.POST)

        if user_form.is_valid():
            username = user_form.cleaned_data.get('username')
            password = user_form.cleaned_data.get('password')
            email = user_form.cleaned_data.get('email')
            address = request.POST.get("address")
            print(username,password,address)
            user_obj = User(username=username,password= password,email=email)
            user_obj.set_password(user_obj.password)
            user_obj.save()
            address = UserAddress(user=user_obj,address=address)
            address.save()
            registered = True
    
            return HttpResponseRedirect(reverse('blog1:congo'))
        else:
            print(user_form.errors)
            return HttpResponse("Some error occured")
    else:

        context={"registered":registered}
        return render(request,'blog1/signup1.html',context)


## this works too
# def registration(request):
#     registered = False
#     if request.method == "POST":
#
#
#         user_form = authenticateform(request.POST)
#
#         if user_form.is_valid():
#             user = user_form.save()
#             user.set_password(user.password)
#             user.save()
#             registered = True
#         else:
#             print(user_form.errors)
#     else:
#         form =  authenticateform()
#         context={'registered':registered,'form':form}
#         return render(request,'blog1/signup1.html',context)
def congo(request):
    return render(request,'blog1/congrats.html',)


@login_required
def postmaker(request):
    return render(request,'blog1/blogs.html')


def update(request,pk):
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        newusername = request.POST.get("username")
        newemail = request.POST.get("email")
        user.username = newusername
        user.email = newemail
        user.save()    
        newaddress= request.POST.get("address")
        n = UserAddress.objects.get( id=pk)
        n.address = newaddress
        n.save()
        return HttpResponseRedirect(reverse('blog1:login'))
    else:   
        return render(request,'blog1/update.html')

def Delete(request,pk):
   
    user = User.objects.get(id=pk)
    logout(request)
    user.delete()
    return HttpResponseRedirect(reverse('blog1:login'))

blog1/templates/blog1/after.html
{% extends "blog1/base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron" id='after'>
    <h1 >Hi</h1>
    <h3>This is my first webisite!!</h3>
    <h3>In this people can write their own stories</h3>
    <h3>I hope you to write some weird stories</h3>

  </div>

</div>
{% endblock %}

blog1/templates/blog1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Metal+Mania&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Piedra&display=swap" rel="stylesheet">
    <meta charset="utf-8">
    <title>Blog</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id='mav'>


        <button class="navbar-toggler " id = 'hello11'  type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog1:after' %}">About<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/Rahulvvsv">Github</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" disabled href="#">LinkedIn</a>
            </li>

          </ul>
          {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"   >
              <a class="nav-link" href="{% url 'blog1:login' %}">{{user.username}}</a>
            </li>
          </ul>
          {% else%}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"   >
              <a class="nav-link" href="{% url 'blog1:login' %}">Login</a>
            </li>
          </ul>
          {% endif %}

        </div>



      </nav>

    {% block content %}
    {% endblock %}



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>
</html>

blog1/templates/blog1/blogs.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/landing.css' %}">
      <link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Metal+Mania&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Piedra&display=swap" rel="stylesheet">
    <title>Blogs</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id='mav'>

        <button class="navbar-toggler " id = 'hello11'  type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog1:after' %}">About<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/Rahulvvsv">Github</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">LinkedIn</a>
            </li>

          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated   %}
            <li class="nav-item active">
            <a class="nav-link" href="{% url "blog1:logout" %}">Logout<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
          </ul>
        </div>


      </nav>
      <div class="container">
        <div class="jumbotron" id='welcome'>
          <h1>Welcome {{user.username}}</h1>
         <h1>Your email is {{user.email}}</h1>
         <h1>Your address is {{user.stories.address}}</h1>
        <a href="{% url 'blog1:update' user.stories.id %}">update account details</a>
           <hr> <a href="{% url 'blog1:delete' user.id %}" >Delete user</a>
        </div>
        <hr>
   

      </div>

blog1/templates/blog1/congrats.html
{% extends "blog1/base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Thank you for registering!!!</h1>
    <h3>You can now Login </h3>

  </div>

</div>
{% endblock %}

blog1/templates/blog1/login.html
{% extends "blog1/base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron" id='when'>

    <h1>Please Login:</h1>
    <!-- <small>Must be a superuser </small> -->
    <hr>


        <form method='post'>
          {% csrf_token %}
      <div class="form-group row">
        <label for="staticEmail" class="col-sm-2 col-form-label">Username</label>
        <div class="col-sm-10">
          <input type="text"  class="form-control"  name="username"  placeholder="Username">
        </div>
      </div>
      <div class="form-group row">
        <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" id="inputPassword" placeholder="Password" name="pass">
        </div>
      </div>
      <div class="form-group row" id='button'>
      <p text-align='right'><input type="submit" class= 'btn btn-primary '  name="" value="Login"></p>

    </div>

    </form>
    <p></p>
    <small>Don't have an account??  <a href="{% url 'blog1:signup' %}"> signup</a></small>


  </div>
</div>

{% endblock %}

blog1/templates/blog1/signup.html
{% extends "blog1/base.html" %}
{% block content %}
{% if registered %}
  <h1>Thank you for registering</h1>
  {% else %}

  <div class="container">
    <div class="jumbotron">


      <form method='POST'>
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
              {{field.label}}
              {{field}}

            </div>

            <p></p>
            {% endfor %}
              <input type="submit" name="" value="register">
      </form>

    </div>

  </div>
  {% endif %}
{% endblock %}

blog1/templates/blog1/signup1.html
{% extends "blog1/base.html" %}
{% block content %}
  {% if registered %}
  <h1>Thank you for registering</h1>
  {% else %}

  <div class="container">
    <div class="jumbotron" id='where'>


      <form method='POST' >
            {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputEmail1">Username</label>
          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name='username'>

        </div>
        <div class="form-group">
          <label for="exampleInputEmail1">Address</label>
          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name='address'>

        </div>
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"  name="email" >
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password" >
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>

    </div>

  </div>
  {% endif %}
{% endblock %}

blog1/templates/blog1/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/landing.css' %}">
      <link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Metal+Mania&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Piedra&display=swap" rel="stylesheet">
    <title>Blogs</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id='mav'>

        <button class="navbar-toggler " id = 'hello11'  type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog1:after' %}">About<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/Rahulvvsv">Github</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">LinkedIn</a>
            </li>

          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated   %}
            <li class="nav-item active">
            <a class="nav-link" href="{% url "blog1:logout" %}">Logout<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
          </ul>
        </div>


      </nav>
      <div class="container">
        <div class="jumbotron" id='welcome'>
         <form method='POST' >
            {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputEmail1">Username</label>
          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name='username' value = {{user.username}}>

        </div>
        <div class="form-group">
          <label for="exampleInputEmail1">Address</label>
          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name='address' value={{user.stories.address}}>

        </div>
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"  name="email" value={{user.email}} >
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>

    </div>


        </div>
        <hr>
   

      </div>